version: '3.7'
services:
  delivery:
    build: .
    ports:
      - 80:3000
    environment:
      - PORT=3000
      - DB_USERNAME=${DB_USERNAME:-app-delivery}
      - DB_PASSWORD=${DB_PASSWORD:-12345Fvs}
      - DB_NAME=${DB_NAME:-delivery_database}
    env_file:
      - .atlas.env